{{- $resourceControllerName := .Values.resourceController.name -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $resourceControllerName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $resourceControllerName }}
subjects:
- kind: ServiceAccount
  name: {{ $resourceControllerName }}
  namespace: {{ .Release.Namespace }}
