{{- $admissionWebhookName := .Values.admissionWebhook.name -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $admissionWebhookName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ $admissionWebhookName }}
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: {{ $admissionWebhookName }}
